/*Create Tables section */

CREATE TABLE USERS (
	user_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	type varchar(4) NOT NULL,
	status BOOLEAN NOT NULL,
	email varchar(256) NOT NULL,
	firstname varchar(128) NOT NULL,
	lastname varchar(128) NOT NULL,
	password varchar(254) NULL,
	salt varchar(128) NULL,
	PRIMARY KEY (user_id)
);

CREATE TABLE ORDERS (
	order_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	user_id INT NOT NULL,
	address_id INT NOT NULL,
	status varchar(4) NOT NULL,
	timeplaced TIMESTAMP NOT NULL,
	lastupdated TIMESTAMP,
	PRIMARY KEY (order_id)
);

CREATE TABLE ADDRESS (
	address_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	user_id INT NOT NULL,
	address1 varchar(128) NOT NULL,
	city varchar(128) NOT NULL,
	state varchar(128) NOT NULL,
	country varchar(128) NOT NULL,
	zip varchar(40) NOT NULL,
	PRIMARY KEY (address_id)
);

CREATE TABLE ORDERITEMS (
	orderitem_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	order_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	status varchar(4) NOT NULL,
	lastupdated TIMESTAMP,
	PRIMARY KEY (orderitem_id)
);

CREATE TABLE PRODUCT (
	product_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name varchar(128) NOT NULL,
	price FLOAT NOT NULL,
	quantity INT NOT NULL,
	isonline BOOLEAN NOT NULL,
	iskitchen BOOLEAN NOT NULL,
	image_url varchar(254),
	created TIMESTAMP NOT NULL,
	lastupdated TIMESTAMP NOT NULL,
	PRIMARY KEY (product_id)
);

CREATE TABLE CATEGORY (
	category_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name varchar(128) NOT NULL,
	isonline BOOLEAN NOT NULL,
	image_url varchar(254),
	created TIMESTAMP NOT NULL,
	lastupdated TIMESTAMP NOT NULL,
	PRIMARY KEY (category_id)
);

CREATE TABLE PRODUCTCATEGORYASSIGNEMENT (
	product_id INT NOT NULL,
	category_id INT NOT NULL
);

CREATE TABLE USERSROLE (
	role_id INT NOT NULL generated by DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	user_id INT NOT NULL,
	role varchar(10) NOT NULL,
	created TIMESTAMP NOT NULL,
	lastupdated TIMESTAMP,
	PRIMARY KEY (role_id)
);

/* Create Foreign Keys */

ALTER TABLE USERSROLE ADD CONSTRAINT USERSROLE_fk0 FOREIGN KEY(user_id) REFERENCES USERS(user_id);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_fk0 FOREIGN KEY (user_id) REFERENCES USERS(user_id);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_fk1 FOREIGN KEY (address_id) REFERENCES ADDRESS(address_id);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_fk0 FOREIGN KEY (user_id) REFERENCES USERS(user_id);

ALTER TABLE ORDERITEMS ADD CONSTRAINT ORDERITEMS_fk0 FOREIGN KEY (order_id) REFERENCES ORDERS(order_id);

ALTER TABLE ORDERITEMS ADD CONSTRAINT ORDERITEMS_fk1 FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id);

ALTER TABLE PRODUCTCATEGORYASSIGNEMENT ADD CONSTRAINT PRODUCTCATEGORYASSIGNEMENT_fk0 FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id);

ALTER TABLE PRODUCTCATEGORYASSIGNEMENT ADD CONSTRAINT PRODUCTCATEGORYASSIGNEMENT_fk1 FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);

CREATE UNIQUE INDEX USERS_IDX1 on USERS (email);

CREATE UNIQUE INDEX ADDRESS_IDX1 on ADDRESS (user_id, address1, city, state, country, zip);

CREATE UNIQUE INDEX CATEGORY_IDX1 on CATEGORY (name);

CREATE UNIQUE INDEX USERSROLE_IDX1 on USERSROLE (user_id, role);

/* Drop tables section */
drop table orderitems;

drop table orders;

drop table address;

drop table users;

drop table productcategoryassignement;

drop table category;

drop table product;

